### PR TITLE
Fix `readthedocs.yml`

### PR DESCRIPTION
**Pull request by lukashergt**
The docs on readthedocs are currently failing. I suspect this has to do with the missing `build` block specifying what OS to use. Let's see whether this fixes it.

@htjb, could you tell readthedocs to build this branch, please? (alternatively give me the power and I'll fiddle around)

### CODE REVIEW

**Comment by htjb** [comment]
>@htjb, could you tell readthedocs to build this branch, please? (alternatively give me the power and I'll fiddle around)

How do I build the docs for the branch? Never done this before...

**Comment by htjb** [comment]
@lukashergt I gave readthedocs permission to build PRs and refreshed the webhook but not seeing the build here. I can add you as a maintainer on the docs? What's your readthedocs username?

**Comment by lukashergt** [comment]
> @lukashergt I gave readthedocs permission to build PRs and refreshed the webhook but not seeing the build here. 

The builds can be viewed here:
https://readthedocs.org/projects/margarine/builds/

> I can add you as a maintainer on the docs? What's your readthedocs username?

Same as my GitHub username: lukashergt

**Comment by lukashergt** [comment]
Nice, looks like this PR does indeed fix the previously failing docs:
https://readthedocs.org/projects/margarine/builds/

image

**Comment by lukashergt** [comment]
The failed python 3.9 test should be unrelated to this PR. That test also fails on the master branch.

**Comment by htjb** [comment]
Ahh maybe it needed a commit to trigger the build. Thanks for the help with the docs Lukas this is great. Go ahead and merge.

>The failed python 3.9 test should be unrelated to this PR.

Hmm there is a known issue with the tests that needs fixing (just haven't got to it yet). This is new though... looks like tensorflow was updated in the last [few weeks](https://github.com/tensorflow/tensorflow/releases) and its broken something...

You're right though that this is not related to this PR so go ahead and merge. Thanks again!

**Pull request merged**
