### PR TITLE
make full use of autodoc such that cross referencing can find all targets

### PR DESCRIPTION
**Pull request by lukashergt**
This PR is motivated by a docs related issue that came up in handley-lab/anesthetic#353. 

Currently the docs are generated in a way that does not allow cross-referencing of all modules and its members. This PR should (hopefully) remedy that. This comes with the added benefit of simplifying the docs source code, leveraging more of the autodoc power.

### CODE REVIEW

**Comment by htjb** [comment]
Nice this is very cool thanks @lukashergt!

I compiled the docs locally, and I can't see any documentation for the`integrate` function in the `calculate` class in the marginal_stats.py` code. Any thoughts what is going on here?

Should wait for #53 before merging this in.

**Comment by ThomasGesseyJones** [comment]
Just to let you know, PR #53 has now been merged

**Comment by htjb** [comment]
Great looks good thanks again @lukashergt! I sent you a collaborator request so you can squash and merge 🚀

**Comment by htjb** [comment]
Hi @lukashergt I think might need to pull master branch back in but otherwise happy for this to be merged! Thanks again.

**Comment by lukashergt** [comment]
Hi @htjb, sorry I missed the invitation, and it now is expired.

**Comment by htjb** [comment]
@lukashergt No problem! Just re sent it.

**Pull request merged**
