### PR TITLE
fix install requirements

### PR DESCRIPTION
**Pull request by AdamOrmondroyd**
The `install_requires` argument in `setup.py` is missing several requirements which are present in `requirements.txt`: `anesthetic`, `scikit-learn`, `tqdm`, and the platform-specific `tensorflow`.

`torch` was also missing from both `setup.py` and `requirements.txt`.

### CODE REVIEW

**Comment by htjb** [comment]
Nice, thanks @AdamOrmondroyd! Clearly, I have been neglecting the `requirements.txt`. I think `torch` is only required for the tests and there is a `requirement_tests.txt`. Perhaps we could merge the two requirements files?

If you felt like it you could rewrite `tests/clustered_distributions.py` in `tensorflow` rather than `torch`? I stole this code from the link at the top of the file and all it does is generate samples/calculate probabilities for some standard multi-modal examples. Think we only need the `log_prob` functions for the two distributions but not 100% sure.

**Comment by AdamOrmondroyd** [comment]
> Feel free to merge if you're not up for the `clustered_distribution.py` rewrite! Thanks @AdamOrmondroyd!

I'm reluctant to get too involved aha, I only stumbled on this from helping Dily

**Comment by htjb** [comment]
@AdamOrmondroyd No problem hahaa it's not super important!

**Comment by AdamOrmondroyd** [comment]
I don't think I have permission to merge (and I'm partial to a green square)

**Comment by htjb** [comment]
Hmm I think I added you as a collaborator so you can probably do it now...

**Comment by AdamOrmondroyd** [comment]
Hm I don't have a button

**Comment by AdamOrmondroyd** [comment]
Might be worth pushing this to pypi so that `pip install margarine` slays?

**Comment by htjb** [comment]
Yeah I'll sort it! Thanks @AdamOrmondroyd! 😄

**Comment by htjb** [comment]
@AdamOrmondroyd Didn't bump the version number 😢

**Comment by AdamOrmondroyd** [comment]
@htjb needs a test to check it's incremented... just nick the anesthetic one

**Comment by htjb** [comment]
@AdamOrmondroyd Yeah I have one for globalemu thanks to @ThomasGesseyJones who may have also done the anesthetic one as well hahaa. Been on my margarine to-do list but haven't got to it yet.

**Comment by ThomasGesseyJones** [comment]
Hi @AdamOrmondroyd and @htjb , 

PR #53 adds the requested version control workflow (copied from the globalemu repository). Can one of you review the code before I merge?

For the record, I did not write the anesthetic version control workflow, at the time of writing the only workflow I have been involved with for that project was the automatic GitHub release workflow.

**Pull request merged**
